import json

from rag.prompts.grounding_contract import synthesis_grounding_user_block

# Validation lives in pipeline; re-export for callers that expect a single synthesis module surface.
from rag.pipeline.llm_report_output import parse_validate_report_output  # noqa: F401


def _report_output_schema_hint() -> str:
    """Exact JSON shape for ReportOutput (Pydantic-aligned)."""
    return """
Output a single JSON object (no markdown fences, no extra text) with this structure:
{
  "verdict": "MEET" | "PASS" | "FLAG" | "INSUFFICIENT",
  "confidence_score": <float 0.0-1.0>,
  "lane_coverage": <int 0-4>,
  "chunk_count": <int, number of distinct chunk_ids used>,
  "risk_triage": "clean" | "watch" | "flag" | "unknown",
  "probe_questions": [
    "First specific question for the founder call (include [chunk_id: …] when grounded)",
    "Second question — engineering or hiring angle",
    "Third question — news, funding, or strategic narrative"
  ],
  "sections": {
    "executive_summary": { "text": "string", "citations": ["chunk_id", ...], "status": "complete"|"partial"|"preliminary"|"insufficient" },
    "legal_regulatory": { "text": "string", "citations": ["chunk_id", ...], "status": "complete"|"partial"|"preliminary"|"insufficient" },
    "engineering_health": { "text": "string", "citations": ["chunk_id", ...], "status": "complete"|"partial"|"preliminary"|"insufficient" },
    "hiring_trends": { "text": "string", "citations": ["chunk_id", ...], "status": "complete"|"partial"|"preliminary"|"insufficient" },
    "funding_news": { "text": "string", "citations": ["chunk_id", ...], "status": "complete"|"partial"|"preliminary"|"insufficient" }
  },
  "known_unknowns": ["string", ...],
  "disclaimer": "This report is generated by AI from publicly available sources. It is not investment advice. Verify all claims from primary sources before making any investment decision."
}

Rules for this JSON:
- probe_questions: REQUIRED. Exactly three strings. These are the "before the call" questions — sharp and specific. Order: (1) legal/regulatory or its absence, (2) engineering or hiring, (3) news/funding or strategy. Each may end with [chunk_id: <id>] when grounded; omit the citation token only when no chunk supports that question (e.g. asking about missing public GitHub).
  Each question must reference **what the evidence showed or failed to show** (e.g. "Our docket hits only matched the trade name — …" or "No indexed job postings appeared — …"); ban generic prompts like "clarify any legal issues", "approach to hiring", or "any recent developments" unless you tie them to a specific gap named in the chunks.
- risk_triage (one-line posture): clean = no adverse signals in evidence; watch = minor concerns worth monitoring; flag = material adverse signal tied to this entity/domain; unknown = not enough evidence to tell.
- Every factual sentence in each section's "text" must end with [chunk_id: <id>] matching an id from the evidence blocks.
- executive_summary "text": ONE paragraph only (3–4 sentences). Do not put "Before the call, probe:" here — use probe_questions for those three questions. Cite at least 2 distinct chunk_ids in the paragraph.
- "citations" arrays must list only chunk_id strings that appear in the evidence blocks below — each entry is the hex id alone (no "chunk_id:" prefix). In prose, use [chunk_id: <hex>] with <hex> exactly as in the evidence header; never [chunk_id: chunk_id: …] or any nested label.
- "sections" must contain exactly the five keys above.
- If exactly one chunk supports a section, set that section's status to "preliminary". If no chunk supports a section, set that section's status to "insufficient" and you may use "Insufficient data" in that section's text only.
- confidence_score reflects evidence **quality**, not raw chunk count: many weak or ambiguous identity matches should lower the score; thin but on-point citations may be 0.3–0.5; do not use 0.0 merely because text is short metadata.
- If the evidence blocks contain only ONE distinct chunk_id, you MUST NOT output verdict "MEET" (not enough independent cross-lane proof). Use "PASS" or "INSUFFICIENT" instead.
""".strip()


def build_synthesis_messages(
    company_name: str,
    *,
    domain: str = "",
    query: str = "full due diligence",
    labeled_evidence: str | None = None,
    context: str | None = None,
    chunk_ids: list[str],
    indexed_chunk_count: int,
    signal_lane_count: int,
    live_web_urls: list[str] | None = None,
    scan_id: str = "",
    entity_id: str = "",
) -> list[dict[str, str]]:
    """Build OpenAI/Groq-style messages; same user prompt as production (via synthesis_prompt)."""
    del scan_id, entity_id  # accepted for ad-hoc test scripts; unused
    blocks = labeled_evidence if labeled_evidence is not None else context
    if blocks is None:
        blocks = ""
    from rag.prompts.system import SYSTEM_PROMPT

    user = synthesis_prompt(
        company_name,
        query,
        labeled_evidence=blocks,
        indexed_chunk_count=indexed_chunk_count,
        live_web_urls=live_web_urls,
        evidence_chunk_count=len(chunk_ids),
        signal_lane_count=signal_lane_count,
        domain=domain,
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user},
    ]


def synthesis_prompt(
    company_name: str,
    query: str,
    *,
    labeled_evidence: str,
    indexed_chunk_count: int = 0,
    live_web_urls: list[str] | None = None,
    evidence_chunk_count: int = 0,
    signal_lane_count: int = 0,
    domain: str = "",
) -> str:
    live_web_urls = live_web_urls or []
    has_live = len(live_web_urls) > 0
    empty_index = indexed_chunk_count == 0
    url_json = json.dumps(live_web_urls[:12])
    domain_display = (domain or "").strip() or "not specified"
    schema = _report_output_schema_hint()
    grounding = synthesis_grounding_user_block()
    chunk_count = max(0, int(evidence_chunk_count))
    lane_count = max(0, int(signal_lane_count))

    if empty_index and has_live:
        live_prefix = f"""
NO QDRANT / INDEX HITS — ONE LIVE WEB SNAPSHOT ONLY:
- Executive_summary must explain clearly: the DealScannr retrieval index returned **no stored chunks** for this entity, and the report is based on **a single live-captured public page** (still cite its chunk_id on every factual sentence).
- Do **not** write "indexed chunks are empty" if that contradicts citing [chunk_id: …]. Prefer: "No prior indexed corpus for this scan; evidence is one live snapshot" and name the URL domain when helpful.
- Use ONLY claims supported by that snapshot text; do not invent funding rounds, lawsuits, or executives not present there.
- verdict must not be "MEET" when there is only one distinct chunk_id in evidence.
- known_unknowns: list what cannot be verified without indexed filings, courts, GitHub, jobs, etc.
- Citations: chunk_ids from evidence blocks only. URLs context: {url_json}

"""
        return f"""{live_prefix}You are analyzing {company_name} (domain: {domain_display}).

User query: {query}

EVIDENCE ({chunk_count} chunks from {lane_count} connector source(s)):
---
{labeled_evidence}
---

TONE: You are a sharp investment analyst briefing a partner 10 minutes before their first call with this founder. Write in confident, direct prose. No bullet soup in the narrative paragraph. No corporate hedging. Lead with what matters. Sound like a person who read the sources, not a system that indexed them.

Using ONLY the evidence above, write the due-diligence JSON. Each factual sentence in non–executive_summary sections ends with [chunk_id: <id>].

{grounding}

Respond with valid JSON matching this schema exactly:
{schema}
"""

    if empty_index:
        zero_rules = """
ZERO INDEXED SOURCES:
- executive_summary must state no indexed primary-source data for this company.
- Use only the labeled evidence below; if evidence is the synthetic empty marker, set verdict INSUFFICIENT and keep sections minimal.
"""
        return f"""{zero_rules}

User query: {query}

{grounding}

Evidence:
---
{labeled_evidence}
---

{schema}
"""

    main = f"""You are analyzing {company_name} (domain: {domain_display}).

User query: {query}

EVIDENCE ({chunk_count} chunks from {lane_count} connector source(s)):
---
{labeled_evidence}
---

TONE: You are a sharp investment analyst briefing a partner 10 minutes before their first call with this founder. Write in confident, direct prose. No bullet soup in the narrative paragraph. No corporate hedging. Lead with what matters. Sound like a person who read the sources, not a system that indexed them.

INSTRUCTIONS:
Using ONLY the evidence above, write a pre-call intelligence report. For each section:

- WARNING — Some chunks may be about different companies that share a similar name (e.g. "Notion Accessories Inc" vs "Notion Labs Inc"). Only cite chunks where the named legal entity or filing context clearly matches {company_name} at domain {domain_display}. If a chunk names a different legal entity, note the ambiguity in that section rather than asserting it as fact about this company.
- If court or SEC snippets match only a **short or generic** fragment of the company name, treat them as weak identity matches: summarize cautiously in legal_regulatory, prefer PASS/INSUFFICIENT over FLAG, and use probe question (1) to ask the founder to confirm whether those matters involve **this** company (name the case or filing pattern you saw).
- CRITICAL — You MUST output exactly three strings in top-level probe_questions (see JSON schema). executive_summary.text is only the narrative paragraph (no probe bullets in that field).
- Set risk_triage to match evidence: use flag only when a material adverse signal for THIS entity is clear; watch for minor or ambiguous risks; clean when nothing adverse showed up; unknown when coverage is too thin to tell.
- If any chunk relates to that section (even short SEC/GitHub/jobs/news/Wikipedia stubs), synthesize what it supports and cite chunk_ids. Stub lines like "SEC Filing: 10-K filed …" are valid legal_regulatory evidence.
- SEC filing metadata (type, date, file number, URL) counts toward legal_regulatory. Longer SEC risk-factor excerpts count heavily toward legal_regulatory.
- GitHub / engineering connector text counts toward engineering_health.
- Job postings count toward hiring_trends. When there are zero hiring chunks, say listings were not found in the indexed sources — do **not** spin that into implied business problems.
- News, Wikipedia, or web snippets count toward funding_news when they mention narrative, founders, or context; otherwise use executive_summary where appropriate.
- Use the phrase "Insufficient data" in a section's prose only when zero chunks are relevant to that section — not when chunks are thin.
- Every factual sentence outside the executive_summary narrative paragraph must end with [chunk_id: <id>]. probe_questions strings may omit [chunk_id: …] only when no evidence supports that question.
- confidence_score reflects evidence depth: thin but cited facts may be 0.3–0.5.

VERDICT RUBRIC (scan-wide) — must align with the GROUNDING CONTRACT block below:
  FLAG         = litigation or regulatory enforcement **for this same entity** (company + domain). Never FLAG on
                 substring collisions (e.g. "Linear Controls" ≠ "Linear" at linear.app). Uncertain identity → PASS, not FLAG.
  MEET         = positive signals in 2+ lanes, no FLAG
  PASS         = some signal exists, no strong positives, no FLAG (or entity match for adverse findings is unclear)
  INSUFFICIENT = fewer than 3 distinct evidence chunks total in the blocks above (metadata stubs still count as chunks)

When chunk_count is 3 or more, do not output verdict INSUFFICIENT solely because many chunks are short; choose PASS or MEET per the rubric unless FLAG applies.

{grounding}

Respond with valid JSON matching this schema exactly:
{schema}
"""
    return main
